version: "3.8"
services:


  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - sharedNet
  
  mariadb:
    image: mariadb
    ports:
      - "6379:6379"
    networks:
      - sharedNet

networks:
  sharedNet:
    driver: bridge